language: rust
cache: cargo
git:
  depth: 1

env:
  global:
    - CRATE_NAME=optbuilder

stages:
  - test
  - quality_gate

rust:

jobs:
  include:
    - stage: test
      script: cargo test
      os: linux
      rust: nightly
    
    - stage: test
      script: cargo test
      os: linux
      rust: stable

    - stage: quality_gate
      os: linux
      rust: stable
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo clippy -- -D warnings
        - cargo fmt --all -- --check